# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ikuctl < Formula
  desc ""
  homepage "https://github.com/chiselstrike/homebrew-tap"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.4/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "937aa1ec41abf807a0d5c2e65df4c9dd11407ae30175a2c32de1eedc2dc2cb17"

      def install
        bin.install "ikuctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.4/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "dca2def312371883add927eb6b5d866b6870ce5463ef77122f9d661538d51589"

      def install
        bin.install "ikuctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.4/homebrew-tap_Linux_x86_64.tar.gz"
      sha256 "9cbc0d35f20ea8f6dac0b29e6c293ad298d56108b4d85dbb988781bfb285f4bf"

      def install
        bin.install "ikuctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.4/homebrew-tap_Linux_arm64.tar.gz"
      sha256 "9dedef9349e0db3c61303b82f1044820ef059b741d2a6997bc467bd983da9d9a"

      def install
        bin.install "ikuctl"
      end
    end
  end
end
