# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ikuctl < Formula
  desc ""
  homepage "https://github.com/chiselstrike/homebrew-tap"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.3/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "ff204e5b53b4ef87a18a72aed8a7a758ea7dfd2304272dd20ffb2db8c3ccd785"

      def install
        bin.install "ikuctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.3/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "ef5f8094bef531746894f1d2482c22f0f080dae9023752fe9f0c453564ccb07c"

      def install
        bin.install "ikuctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.3/homebrew-tap_Linux_arm64.tar.gz"
      sha256 "2e9facccae8a3dd52165da10fa42027139e446d56ddb15bb09df99f7f57321b3"

      def install
        bin.install "ikuctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.0.3/homebrew-tap_Linux_x86_64.tar.gz"
      sha256 "555e36df74303b1b000f2d91d9c005f4739c6449e217d2793c4c506db2c96b0b"

      def install
        bin.install "ikuctl"
      end
    end
  end
end
