# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tools < Formula
  desc ""
  homepage "https://github.com/chiselstrike/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chiselstrike/homebrew-tools/releases/download/v0.0.1/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "19e3798b739484c87945ed532881145acfea98ab6b2071006debe5898dae2876"

      def install
        bin.install "ikuctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tools/releases/download/v0.0.1/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "b68a57a73f5005683a8cba5e48daecc789019d1807a1ba3cc0e3fb961f4f2047"

      def install
        bin.install "ikuctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiselstrike/homebrew-tools/releases/download/v0.0.1/homebrew-tools_Linux_arm64.tar.gz"
      sha256 "5f0709161af52ef77b7d0718840760b219f65f4ee8a143c9746feb7e18ad035e"

      def install
        bin.install "ikuctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tools/releases/download/v0.0.1/homebrew-tools_Linux_x86_64.tar.gz"
      sha256 "b095d37564293bb2cb5cb678439df8a49c45d0324ef8d48dc9368feb21219433"

      def install
        bin.install "ikuctl"
      end
    end
  end
end
