# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Turso < Formula
  desc ""
  homepage "https://github.com/chiselstrike/homebrew-tap"
  version "0.72.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.72.2/homebrew-tap_Darwin_x86_64.tar.gz"
      sha256 "55d0d698430d132c45ea0615fe67399275a43aa7e4c3e7d9c3ab28beb0bd691e"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.72.2/homebrew-tap_Darwin_arm64.tar.gz"
      sha256 "278f53625baec6790e46f2c267ca9a37a4366f5696194ec576be8508e64b44d6"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.72.2/homebrew-tap_Linux_arm64.tar.gz"
      sha256 "a6a9d8b63a1958aa4265b5b3f08b36e9b590a1f75f182a5ceb010f9f87caa5fb"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/chiselstrike/homebrew-tap/releases/download/v0.72.2/homebrew-tap_Linux_x86_64.tar.gz"
      sha256 "3e2f5c876f49b6d4ced443a5332837b26e3b20b26fabf546ac26a814a9cdc9e3"

      def install
        bin.install "turso"
        bash_completion.install "completions/turso.bash" => "turso"
        zsh_completion.install "completions/turso.zsh" => "_turso"
        fish_completion.install "completions/turso.fish"
      end
    end
  end

  def post_install
    exec('turso quickstart')
  end
end
